# This file was generated by GoReleaser. DO NOT EDIT.
cask "gllm" do
  desc "`gllm` is a powerful command-line tool designed to interact seamlessly with various Large Language Models (LLMs)."
  homepage ""
  version "1.12.16"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gllm"

  on_macos do
    on_intel do
      url "https://github.com/activebook/gllm/releases/download/v1.12.16/gllm_Darwin_x86_64.tar.gz"
      sha256 "2ef86ccf81d49246ccbc0804335407e4146a1fa03463b9b0ff9c6d58e65d6b41"
    end
    on_arm do
      url "https://github.com/activebook/gllm/releases/download/v1.12.16/gllm_Darwin_arm64.tar.gz"
      sha256 "2683a64902bdc9b8587dfd746b293371758a837c8c46dd974a2ec3106152a157"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/activebook/gllm/releases/download/v1.12.16/gllm_Linux_x86_64.tar.gz"
      sha256 "ae637f3d44315e02acb0713aa13af712fa0fcf730d27a3c4180eb3b35a8ec505"
    end
    on_arm do
      url "https://github.com/activebook/gllm/releases/download/v1.12.16/gllm_Linux_arm64.tar.gz"
      sha256 "26ae73c9a76d945f1ebc3c72e4bf5eb6fa5f64b8cba46456178bb9606d5567ce"
    end
  end

  # No zap stanza required
end
