# This file was generated by GoReleaser. DO NOT EDIT.
cask "gllm" do
  name "gllm"
  desc "`gllm` is a powerful command-line tool designed to interact seamlessly with various Large Language Models (LLMs)."
  homepage ""
  version "1.15.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gllm"

  on_macos do
    on_intel do
      url "https://github.com/activebook/gllm/releases/download/v#{version}/gllm_Darwin_x86_64.tar.gz"
      sha256 "e85bc4006b9a9a8316984284538cc46440cc332600ebe311266cd48db210f132"
    end
    on_arm do
      url "https://github.com/activebook/gllm/releases/download/v#{version}/gllm_Darwin_arm64.tar.gz"
      sha256 "cbe948d19dc0eeef926d622b40915a24471b30a99b6c7e25687159768e1186d2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/activebook/gllm/releases/download/v#{version}/gllm_Linux_x86_64.tar.gz"
      sha256 "186edee8cd41ad6156ed5f0cd67e5431e25735aa0428d34b5cedaf981ca2ecad"
    end
    on_arm do
      url "https://github.com/activebook/gllm/releases/download/v#{version}/gllm_Linux_arm64.tar.gz"
      sha256 "175e584288aacd4933b9bf230a18c3824fd766c0ac240755019aee2083fcc7e1"
    end
  end

  # No zap stanza required
end
